server:
  port: 8848
spring:
  #??SpringBoot2.6.0?????swagger?????????springboot2.6.0??????SpringMVC ?????????AntPathMatcher ???PathPatternParser?????????????????AntPathMatcher?
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #?????
  datasource:
    #???????
    type: com.zaxxer.hikari.HikariDataSource
    #?????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/administrator?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: root

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  thymeleaf:
    #???????? HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #?? ?????
    encoding: UTF-8
    #?????false,?????????????
    cache: false
    #??????????templates???????
    prefix: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    #????????
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    #??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml